-   id: ast-grep
    name: ast-grep
    description: "ast-grep scan"
    entry: sg scan --report-style=short
    language: node
    types: ["text"]
    require_serial: false
    additional_dependencies: ["@ast-grep/cli@0.27.1"]
    minimum_pre_commit_version: "0"
