name: Test hook integration

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
      with:
        enable-cache: true
        cache-suffix: "precommit"
        cache-dependency-glob: tests/.pre-commit-config.yaml

    - name: Cache pre-commit
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

    - name: Check hook pass
      shell: bash
      run: uvx pre-commit run --config "tests/.pre-commit-config.yaml" --all-files ast-grep-pass

    - name: Check hook failure
      shell: bash
      run: |
        set +e
        uvx pre-commit run --config "tests/.pre-commit-config.yaml" --all-files ast-grep-fail
        if [[ "$?" == "0" ]]; then exit 1; fi
        echo "::notice::Hook failed as expected"
