name: "Tests"

on:
    push:
        branches:
            - main
            - dev
            - develop
    pull_request:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: "15 7 */7 * *"

jobs:
    pre-commit:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - uses: ./.github/actions/test-hooks
