name: "Tests"

on:
    push:
        branches:
            - main
            - dev
            - develop
    pull_request:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: "15 7 */7 * *"

jobs:
    pre-commit:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            - uses: ./.github/actions/test-hooks
