name: "Tests"

on:
    push:
        branches:
            - main
            - dev
            - develop
    pull_request:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: "15 7 */7 * *"

jobs:
    pre-commit:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
            - uses: ./.github/actions/test-hooks
